//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.14
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 741daa04-7e74-4c50-a37c-b9f6734bdee1 aws-my-sample-app-android-v0.14";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:898f9bab-0624-45d6-9a25-146caa29a6c0";
    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
        "whosatmyparty-contentdelivery-mobilehub-206667507";
    public static final Regions AMAZON_CONTENT_DELIVERY_S3_REGION =
       Regions.fromName("us-east-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_ABadiKgo8";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "3suq0elmas17348n81dv24ei7";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "shd4p86jr0gn0gv278p1d01uvde49fegv2r0qlqkt3mt6mffhkc";
}
