package com.amazonaws.mobile.api;

//
//  CloudLogicAPIFactory.java
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.14
//

/**
 * Produces instances of Cloud Logic API configuration.
 */
public class CloudLogicAPIFactory {

    private CloudLogicAPIFactory() {}

    /**
     * Gets the configured micro-service instances.
     * @return
     */
    public static CloudLogicAPIConfiguration[] getAPIs() {
        final CloudLogicAPIConfiguration[] apis = new CloudLogicAPIConfiguration[] {
                new CloudLogicAPIConfiguration("api",
                                              "Quebec's api",
                                              "https://dchsefy4f7.execute-api.eu-west-1.amazonaws.com/Development",
                                              new String[] {
                                                  "/api",
                                                  "/api/123",
                                              },
                                              com.amazonaws.mobile.api.iddchsefy4f7.ApiMobileHubClient.class),
        };

        return apis;
    }
}
