//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.14
//
package com.quebec.app.auth;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import com.amazonaws.mobile.user.signin.CognitoUserPoolsSignInProvider;
import com.mobsandgeeks.saripaar.annotation.ConfirmPassword;
import com.mobsandgeeks.saripaar.annotation.Email;
import com.mobsandgeeks.saripaar.annotation.NotEmpty;
import com.mobsandgeeks.saripaar.annotation.Password;
import com.quebec.app.R;
import com.quebec.app.util.ViewHelper;

import com.mobsandgeeks.saripaar.*;

import java.util.List;

/**
 * Activity to prompt for account sign up information.
 */
public class SignUpActivity extends Activity implements Validator.ValidationListener {
    /** Log tag. */
    private static final String LOG_TAG = SignUpActivity.class.getSimpleName();

    private Validator val;

    @NotEmpty
    private EditText username;

    @NotEmpty
    @Password(min = 8, scheme = Password.Scheme.ALPHA_NUMERIC_MIXED_CASE_SYMBOLS)
    private EditText password;

    @ConfirmPassword
    private EditText confirmPassword;

    @NotEmpty
    private EditText name;

    @NotEmpty
    @Email
    private EditText email;

    private TextView error;

    @Override
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sign_up);

        val = new Validator(this);
        val.setValidationListener(this);

        username = (EditText) this.findViewById(R.id.signup_username);
        password = (EditText) this.findViewById(R.id.signup_password);
        confirmPassword = (EditText) this.findViewById(R.id.signup_password_confirm);
        name = (EditText) this.findViewById(R.id.signup_given_name);
        email = (EditText) this.findViewById(R.id.signup_email);

        error = (TextView) this.findViewById(R.id.signup_error);
    }

    /**
     * Retrieve input and return to caller.
     * @param view the Android View
     */
    public void signUp(final View view) {
        val.validate();
    }


    /**
     * When the validation checks have succeeded, send the intent to the Amazon login handler.
     */
    @Override
    public void onValidationSucceeded() {
        final String username = ViewHelper.getStringValue(this, R.id.signup_username);
        final String password = ViewHelper.getStringValue(this, R.id.signup_password);
        final String givenName = ViewHelper.getStringValue(this, R.id.signup_given_name);
        final String email = ViewHelper.getStringValue(this, R.id.signup_email);

        final Intent intent = new Intent();
        intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.USERNAME, username);
        intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.PASSWORD, password);
        intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.GIVEN_NAME, givenName);
        intent.putExtra(CognitoUserPoolsSignInProvider.AttributeKeys.EMAIL_ADDRESS, email);

        setResult(RESULT_OK, intent);

        finish();
    }

    /**
     * If the validation checks failed, then show the error messages on the page.
     * @param errors given from the validation checker.
     */
    @Override
    public void onValidationFailed(List<ValidationError> errors) {
        for (ValidationError error : errors) {
            View view = error.getView();
            String message = error.getCollatedErrorMessage(this);

            // Display error messages ;)
            if (view instanceof EditText) {
                ((EditText) view).setError(message);
            } else {
                Toast.makeText(this, message, Toast.LENGTH_LONG).show();
            }
        }
    }
}
